# 配置端口
server:
  port: 8080
spring:
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hrm_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
