server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql//localhost:3306/blogs_system?useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: 123456


